# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66f8cc3389fbff3084fb37d360375dccba6a9fb07659e795b85b5380bb0b9b78ad6feea9f5b581ceb2fcc81e0b150423dd71a2105bd0fdc3e88c573e8d53c158

test:
  secret_key_base: ccf3a2b248e81fc5821db64bf99178fdc97dc8199524886ba42dce022f893bfd2369b7bb96aeac29318fb42577767ba27f837c27b2072ab025b63943974b17f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
